import{a as L,S as x,i as l}from"./assets/vendor-5YrzWRhu.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const c of a.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function s(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function n(t){if(t.ep)return;t.ep=!0;const a=s(t);fetch(t.href,a)}})();const w=L.create({baseURL:"https://pixabay.com/api/",params:{key:"51736098-e561806c369733f177830f298",image_type:"photo",orientation:"horizontal",safesearch:!0}});async function u(e,r,s=15){return(await w.get("",{params:{q:e,page:r,per_page:s}})).data}const y=document.querySelector(".gallery");let v=new x(".gallery a");function g(e){const r=e.map(s=>`<li class="gallery-item">
            <a class="gallery-link" href="${s.largeImageURL}">
            <img
            class="gallery-image"
            src="${s.webformatURL}"
            data-source="${s.largeImageURL}"
            alt="${s.tags}"
            />
            <div class = "gallery-box">
            <p class="gallery-box-text">Likes <span class="gallery-box-span">${s.likes}</span></p>
            <p class="gallery-box-text">Views <span class="gallery-box-span">${s.views}</span></p>
            <p class="gallery-box-text">Comments <span class="gallery-box-span">${s.comments}</span></p>
            <p class="gallery-box-text">Downloads <span class="gallery-box-span">${s.downloads}</span></p>
            </div>
            </a>
            </li>`).join("");y.insertAdjacentHTML("beforeend",r),v.refresh()}function S(){y.innerHTML=""}function p(){document.querySelector(".loader").classList.remove("is-hidden")}function f(){document.querySelector(".loader").classList.add("is-hidden")}function q(){document.querySelector(".btn-load").classList.remove("is-hidden")}function m(){document.querySelector(".btn-load").classList.add("is-hidden")}function h(e,r,s=15){const n=Math.ceil(e/s);r<n?q():(m(),iziToast.info({message:"We're sorry, but you've reached the end of search results."}))}function $(){const{height:e}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}const E=document.querySelector(".form"),M=document.querySelector(".btn-load");let i="",o=1;const b=15;let d=0;E.addEventListener("submit",async e=>{if(e.preventDefault(),i=e.target.elements.searchText.value.trim(),i===""){l.warning({title:"Warning",message:"Empty input field"});return}o=1,S(),p(),m();try{const r=await u(i,o,b);if(d=r.totalHits,r.hits.length===0){l.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}else g(r.hits),h(d,o)}catch{l.error({message:"An error occurred while fetching images. Please try again."})}finally{f()}e.target.reset()});M.addEventListener("click",async()=>{o+=1,p();try{const e=await u(i,o,b);g(e.hits),h(d,o),$()}catch{l.error({message:"An error occurred while fetching images. Please try again."})}finally{f()}});
//# sourceMappingURL=index.js.map
